apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-pos-config
  namespace: "${NAMESPACE}"
data:
  DB_BACKEND: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "1"
  ENVIRONMENT: "production"
  TZ: "${TZ}"