apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: "${NAMESPACE}"
data:
  DB_BACKEND: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  ENVIRONMENT: "production"
  FRONTEND_PROJECT_NAME: "${FRONTEND_PROJECT_NAME}"